//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int IdClient { get; set; }
        public Nullable<int> Treiner { get; set; }
        public int Discounts { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TrainingId { get; set; }
    
        public virtual Discounts Discounts1 { get; set; }
        public virtual Trainer Trainer { get; set; }
        public virtual Training Training { get; set; }
        public virtual Users Users { get; set; }
    }
}
