//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercises
    {
        public int IdExercises { get; set; }
        public string NameExercises { get; set; }
        public string Duration { get; set; }
        public string Replays { get; set; }
        public int TraningId { get; set; }
        public string RegularityExercises { get; set; }
    
        public virtual Training Training { get; set; }
    }
}
