//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int IdRequest { get; set; }
        public string Target { get; set; }
        public int StatusId { get; set; }
        public int ClientId { get; set; }
        public int TrenerId { get; set; }
    
        public virtual Stuts Stuts { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
