//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TrainingDetails
    {
        public int IdTraining { get; set; }
        public string Name { get; set; }
        public string NameExercises { get; set; }
        public int Duration { get; set; }
        public string RegularityExercises { get; set; }
        public int Replays { get; set; }
        public int Quantity { get; set; }
        public int Progress { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> DoneExercises { get; set; }
        public int ExercisesId { get; set; }
        public int TrenerId { get; set; }
    }
}
